### ISSUE TITLE
alpine install error

### ISSUE THREAD

**Issue by wirwolf** [dmitry-ee/tendermint-prometheus-exporter#14]
```
/app # apk add curl
ERROR: Unable to lock database: No such file or directory
ERROR: Failed to open apk database: No such file or directory
/app # 
```
remove line 
```
rm -rf /lib/apk/db
```
or create an empty directory after rm

**Comment by dmitry-ee** [comment]
@wirwolf thanks for noticing!
I was pursued by idea to making smallest possible image and forgot about image re-usability.
Fixed with version [0.9.32](https://github.com/dmitry-ee/tendermint-prometheus-exporter/pull/15/commits/9c1fda136b127cebd3c3f56dcaa6e2c82cbcd841)
